const demoParticipants = [
  { id:'demo-julia', name:'Julia Werner', email:'julia@example.de', week:7, status:'WEEK_7', progress:79, clarity:'3 → 7', next:'Entscheidung A / B', initials:'JW' },
  { id:'demo-david', name:'David Klein', email:'david@example.de', week:5, status:'WAITING_FOR_UPLOAD', progress:56, clarity:'2 → 5', next:'Grabrede hochladen', initials:'DK' },
  { id:'demo-leonie', name:'Leonie Schmitt', email:'leonie@example.de', week:8, status:'FINAL_CALL_REQUIRED', progress:96, clarity:'4 → 9', next:'Abschlusscall planen', initials:'LS' },
  { id:'demo-tobias', name:'Tobias Wolf', email:'tobias@example.de', week:3, status:'WEEK_3', progress:34, clarity:'2 → 3', next:'Top 5 Motivatoren', initials:'TW' },
];
let participants = [...demoParticipants];
let programSnapshot = null;
let users = [];
let leads = [];
const titles = { command:'Command Center', participants:'Kunden', clarity:'Klarheitsanalyse', gates:'Wochen-Gates', escalations:'Coach-Eskalationen', leads:'Interessenten', users:'Benutzer', settings:'Einstellungen' };
const contextNavigation = {
  command:{icon:'⌂',label:'Übersicht',items:[['Dashboard','Kennzahlen & Entwicklung','.metrics'],['Prozesssteuerung','Kunden im Prozess','.main-grid'],['Klarheitsentwicklung','Messung & Wochenverteilung','.lower-grid']]},
  participants:{icon:'◎',label:'Verwaltung',items:[['Übersicht','Status aller Kunden','.intro'],['Kundenliste','Suchen, filtern und öffnen','.participant-table'],['Programmsteuerung','Wochen & Freigaben verwalten','.participant-table']]},
  clarity:{icon:'✦',label:'Auswertung',items:[['Gesamtbild','Aktueller Arbeitsstand','.analysis-hero'],['Evidenz','Muster & Spannungsfelder','.evidence-grid'],['Dein-Ding-Map','Vier Bereiche im Überblick','.map'],['Finale Optionen','Vergleich und Bewertung','.options']]},
  gates:{icon:'✓',label:'Prozessqualität',items:[['Gate-Übersicht','Alle Prozesswochen','.gate-grid'],['Aktuelle Phase','Offene Pflichtschritte','.gate-card.current'],['Abgeschlossen','Bestätigte Wochen','.gate-card.complete']]},
  escalations:{icon:'!',label:'Begleitung',items:[['Übersicht','Alle Coach-Fälle','.escalation-grid'],['Dringende Fälle','Entscheidung erforderlich','.urgent'],['Gesprächsplanung','Persönlich weiterhelfen','.escalation-grid']]},
  leads:{icon:'↗',label:'Vertrieb',items:[['Interessentenübersicht','Alle Anfragen','.participant-table'],['Offene Kontakte','Qualifizieren & bearbeiten','.participant-table'],['Termine','Calendar & Meet planen','.participant-table'],['Kundenaktivierung','Nach dem Kauf freischalten','.participant-table']]},
  users:{icon:'♙',label:'Zugänge',items:[['Benutzerübersicht','Konten und Status','.participant-table'],['Rollen & Rechte','Zugänge bearbeiten','.participant-table'],['Programmzugänge','Kundenprogramme verwalten','.participant-table']]},
  settings:{icon:'⚙',label:'Konfiguration',items:[['Allgemein','Arbeitsbereich & System','.settings-content','general'],['Termine','Verfügbarkeit & Regeln','.settings-content','appointments'],['Integrationen','Google Calendar & Meet','.settings-content','integrations'],['Klarheitsanalyse','Fragen des Prozesses','.settings-content','questions'],['Benutzer & Zugänge','Rollen & Programme','.settings-content','access']]}
};
const gateData = [
  ['0','Onboarding',['Datenschutz aktiv bestätigt','Start-Commitment unterschrieben']],
  ['1','Ausgangslage',['Drei Wünsche vertieft','Zielzustand & Baseline','Werdegang vollständig']],
  ['2','Fähigkeiten & Umfeld',['Formales/informelles Können','Selbst- und Fremdbild','Aktuelles Ziel']],
  ['3','Motivatoren',['Top 5 priorisiert','Kindheitsinteressen','Reintegration gewählt']],
  ['4','Halbzeit',['HD technisch verarbeitet','Ding/Leben-Zuordnung','Halbzeitbericht erzeugt']],
  ['5','Werte & Lebenswerk',['Top 5 Werte','LILA abgeschlossen','Grabrede hochgeladen']],
  ['6','Dein-Ding-Map',['Vier Bereiche','10+ Ausschlusskriterien','Positivkriterien & Map']],
  ['7','Optionen & Realität',['Mind. ein Realitätskontakt','Genau zwei Optionen','Entscheidung oder Eskalation']],
  ['8','Umsetzung',['24/30/90-Tage-Plan','Commitment unterschrieben','Dossier & Abschlusscall']],
];

function escapeHtml(value=''){const span=document.createElement('span');span.textContent=String(value);return span.innerHTML;}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600);}
function renderContextNavigation(name){const config=contextNavigation[name]||contextNavigation.command;document.querySelector('#contextIcon').textContent=config.icon;document.querySelector('#contextTitle').textContent=titles[name]||titles.command;const nav=document.querySelector('#contextNav');nav.innerHTML=`<p>${escapeHtml(config.label)}</p><nav>${config.items.map(([title,description,target,settings],index)=>`<button class="${index===0?'active':''}" data-context-target="${escapeHtml(target)}" ${settings?`data-context-settings="${escapeHtml(settings)}"`:''}><span>${String(index+1).padStart(2,'0')}</span><div><b>${escapeHtml(title)}</b><small>${escapeHtml(description)}</small></div></button>`).join('')}</nav>`;nav.querySelectorAll('[data-context-target]').forEach(button=>button.addEventListener('click',()=>{nav.querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button));if(button.dataset.contextSettings)showSettingsPanel(button.dataset.contextSettings);const target=document.querySelector(`.view.active ${button.dataset.contextTarget}`);target?.scrollIntoView({behavior:'smooth',block:'start'});}));}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.panel===name));document.querySelectorAll('.sidebar nav button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));document.querySelector('#viewTitle').textContent=titles[name];renderContextNavigation(name);window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view)));
document.querySelectorAll('[data-jump]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.jump)));
function showSettingsPanel(name){document.querySelectorAll('[data-settings-panel]').forEach(panel=>panel.classList.toggle('active',panel.dataset.settingsPanel===name));document.querySelectorAll('[data-settings-tab]').forEach(button=>button.classList.toggle('active',button.dataset.settingsTab===name));if(name==='questions')loadClarityQuestions();}
document.querySelectorAll('[data-settings-tab]').forEach(button=>button.addEventListener('click',()=>showSettingsPanel(button.dataset.settingsTab)));
document.querySelectorAll('[data-settings-jump]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.settingsJump)));
renderContextNavigation('command');

let clarityQuestions=[];
let clarityQuestionsLoaded=false;
const clarityTypeLabels={dialog:'Dialogfrage',scale:'Skala',upload:'Upload-Hinweis',confirmation:'Bestätigung',external:'Technischer Schritt',structured:'Strukturierter Schritt'};
function renderClarityQuestions(){const list=document.querySelector('#clarityQuestionList');if(!list)return;const week=document.querySelector('#clarityQuestionWeek')?.value||'';const query=(document.querySelector('#clarityQuestionSearch')?.value||'').trim().toLowerCase();const filtered=clarityQuestions.filter(item=>(!week||String(item.week)===week)&&(!query||`${item.title} ${item.prompt_text}`.toLowerCase().includes(query)));document.querySelector('#clarityQuestionCount').textContent=`${filtered.length} von ${clarityQuestions.length} Fragen`;list.innerHTML=filtered.length?filtered.map(item=>`<form class="clarity-question-card" data-question-key="${escapeHtml(item.question_key)}"><div class="question-card-head"><div><span>Woche ${Number(item.week)} · Schritt ${Number(item.sort_order)}</span><h4>${escapeHtml(item.title)}</h4></div><i>${escapeHtml(clarityTypeLabels[item.prompt_type]||item.prompt_type)}</i></div><label>Frage oder Arbeitsanweisung<textarea name="promptText" rows="3" minlength="5" maxlength="2000" required>${escapeHtml(item.prompt_text)}</textarea></label><div class="question-card-actions"><small>${item.prompt_text===item.default_prompt_text?'Standardfrage':'Individuell angepasst'}${item.updated_at?` · ${new Date(item.updated_at).toLocaleString('de-DE')}`:''}</small><div><button class="secondary" type="button" data-reset-question>Standard wiederherstellen</button><button class="primary" type="submit">Frage speichern</button></div></div></form>`).join(''):'<div class="empty">Keine Fragen für diesen Filter gefunden.</div>';}
async function loadClarityQuestions(force=false){if(clarityQuestionsLoaded&&!force){renderClarityQuestions();return;}const list=document.querySelector('#clarityQuestionList');if(list)list.innerHTML='<div class="empty">Klarheitsfragen werden geladen …</div>';try{const response=await fetch('/api/clarity-settings');const data=await response.json();if(!response.ok)throw new Error(data.error);clarityQuestions=data.questions||[];clarityQuestionsLoaded=true;renderClarityQuestions();}catch(error){if(list)list.innerHTML=`<div class="empty">${escapeHtml(error.message||'Klarheitsfragen konnten nicht geladen werden.')}</div>`;}}
async function updateClarityQuestion(form,action='save'){const questionKey=form.dataset.questionKey;const button=form.querySelector(action==='reset'?'[data-reset-question]':'button[type="submit"]');const promptText=form.elements.promptText.value.trim();button.disabled=true;try{const response=await fetch('/api/clarity-settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionKey,promptText,action})});const data=await response.json();if(!response.ok)throw new Error(data.error);const index=clarityQuestions.findIndex(item=>item.question_key===questionKey);if(index>=0)clarityQuestions[index]={...clarityQuestions[index],...data.question};renderClarityQuestions();toast(action==='reset'?'Standardfrage wurde wiederhergestellt.':'Klarheitsfrage wurde gespeichert.');}catch(error){toast(error.message||'Klarheitsfrage konnte nicht gespeichert werden.');button.disabled=false;}}
document.querySelector('#clarityQuestionWeek')?.addEventListener('change',renderClarityQuestions);
document.querySelector('#clarityQuestionSearch')?.addEventListener('input',renderClarityQuestions);
document.querySelector('#clarityQuestionList')?.addEventListener('submit',event=>{const form=event.target.closest('[data-question-key]');if(!form)return;event.preventDefault();updateClarityQuestion(form);});
document.querySelector('#clarityQuestionList')?.addEventListener('click',event=>{const button=event.target.closest('[data-reset-question]');if(!button)return;const form=button.closest('[data-question-key]');if(confirm('Diese Frage wirklich auf den ausgelieferten Standard zurücksetzen?'))updateClarityQuestion(form,'reset');});

function accessModeLabel(mode){return mode==='time_based'?'Zeitbasiert':mode==='full_access'?'Alles freigegeben':'Abschlussbasiert';}
function participantMarkup(person, table=false){const info=`<div class="participant"><span class="avatar">${escapeHtml(person.initials)}</span><div><strong>${escapeHtml(person.name)}</strong><small>${escapeHtml(person.email)}</small></div></div>`;if(table)return `<div class="table-data participant-control-row" data-participant-id="${escapeHtml(person.id)}">${info}<span class="phase"><b>${person.week?`Woche ${person.week}`:'Onboarding'}</b>${escapeHtml(person.programStatus||person.status)}</span><div><div class="progress"><i style="width:${person.progress}%"></i></div><div class="progress-label">${person.progress}% · ${escapeHtml(accessModeLabel(person.accessMode))}</div></div><strong>${person.startDate?new Date(`${person.startDate}T00:00:00`).toLocaleDateString('de-DE'):'—'}</strong><span class="gate"><button class="program-open" data-program-id="${escapeHtml(person.id)}">Programm steuern →</button></span></div>`;return `<div class="participant-row">${info}<span class="phase"><b>Woche ${person.week}</b>${escapeHtml(accessModeLabel(person.accessMode))}</span><div><div class="progress"><i style="width:${person.progress}%"></i></div><div class="progress-label">${person.progress}%</div></div><span class="gate"><b>${escapeHtml(person.next)}</b>${escapeHtml(person.programStatus||'aktiv')}</span></div>`;}
function renderParticipants(){const query=document.querySelector('#participantSearch')?.value.toLowerCase()||'',week=document.querySelector('#weekFilter')?.value||'';const filtered=participants.filter(p=>(!query||`${p.name} ${p.email}`.toLowerCase().includes(query))&&(!week||String(p.week)===week));document.querySelector('#dashboardParticipants').innerHTML=participants.slice(0,4).map(p=>participantMarkup(p)).join('');document.querySelector('#participantRows').innerHTML=filtered.length?filtered.map(p=>participantMarkup(p,true)).join(''):'<div class="empty">Keine Kunden gefunden.</div>';document.querySelectorAll('[data-program-id]').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();openProgramControl(button.dataset.programId);}));document.querySelectorAll('.participant-control-row').forEach(row=>row.addEventListener('click',()=>openProgramControl(row.dataset.participantId)));}
document.querySelector('#participantSearch').addEventListener('input',renderParticipants);document.querySelector('#weekFilter').addEventListener('change',renderParticipants);
document.querySelector('#gateGrid').innerHTML=gateData.map(([week,title,items],index)=>`<article class="gate-card ${index<3?'complete':index===3?'current':''}"><div class="gate-top"><span>${week==='0'?'Start':`Woche ${week}`}</span><i>${index<3?'Abgeschlossen':index===3?'Aktiv':'Gesperrt'}</i></div><h2>${title}</h2><p>${index<3?'Alle Pflichtschritte technisch bestätigt.':index===3?'Aktuelle Prozessphase der ausgewählten Person.':'Wird erst nach bestandenem vorherigem Gate geöffnet.'}</p><ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul></article>`).join('');

const participantDialog=document.querySelector('#participantDialog');document.querySelector('#participantForm [name="programStartDate"]').value=new Date().toISOString().slice(0,10);document.querySelectorAll('[data-open-participant]').forEach(b=>b.addEventListener('click',()=>participantDialog.showModal()));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>participantDialog.close()));
document.querySelector('#participantForm').addEventListener('submit',async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));try{const response=await fetch('/api/participants',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const data=await response.json();if(!response.ok)throw new Error(data.error);participantDialog.close();event.currentTarget.reset();toast('Kunde wurde im Onboarding angelegt.');await loadParticipants();}catch(error){toast(error.message);}});
const selectedPermissions=form=>[...form.querySelectorAll('[name="permissions"]:checked')].map(input=>input.value);
const userDialog=document.querySelector('#userDialog');document.querySelector('#openUser').addEventListener('click',()=>userDialog.showModal());document.querySelectorAll('[data-close-user]').forEach(b=>b.addEventListener('click',()=>userDialog.close()));document.querySelector('#userForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));values.permissions=selectedPermissions(form);const response=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});const data=await response.json();if(!response.ok)return toast(data.error);userDialog.close();form.reset();toast(data.passwordResetSent?'Benutzer angelegt. Passwort-E-Mail wurde versendet.':'Benutzer mit Startpasswort wurde angelegt.');loadUsers();});
const userEditDialog=document.querySelector('#userEditDialog');const userEditForm=document.querySelector('#userEditForm');document.querySelectorAll('[data-close-user-edit]').forEach(button=>button.addEventListener('click',()=>userEditDialog.close()));
function openUserEdit(id){const user=users.find(item=>item.id===id);if(!user)return;userEditForm.elements.id.value=user.id;userEditForm.elements.role.value=user.role;userEditForm.elements.status.value=user.status;document.querySelector('#editUserName').textContent=user.name;document.querySelector('#editUserEmail').textContent=user.email;userEditForm.querySelectorAll('[name="permissions"]').forEach(input=>{input.checked=(user.permissions||[]).includes(input.value);});userEditDialog.showModal();}
userEditForm.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const payload={id:form.elements.id.value,role:form.elements.role.value,status:form.elements.status.value,permissions:selectedPermissions(form)};const response=await fetch('/api/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)return toast(data.error);userEditDialog.close();toast('Benutzerrechte wurden gespeichert.');loadUsers();});
document.querySelector('#resetUserPassword').addEventListener('click',async()=>{const response=await fetch('/api/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:userEditForm.elements.id.value,action:'password_reset'})});const data=await response.json();toast(response.ok?'Passwort-Reset wurde per E-Mail versendet.':data.error);});

const programDialog=document.querySelector('#programDialog');
document.querySelectorAll('[data-close-program]').forEach(button=>button.addEventListener('click',()=>programDialog.close()));
function renderProgramControl(data){
  programSnapshot=data;
  document.querySelector('#programParticipantId').value=data.profile.id;
  document.querySelector('#programParticipantName').textContent=data.profile.name;
  document.querySelector('#programParticipantEmail').textContent=data.profile.email;
  document.querySelector('#programStartDate').value=data.access.programStartDate||new Date().toISOString().slice(0,10);
  document.querySelector('#programStatus').value=data.access.status;
  document.querySelector('#programCurrentWeek').value=String(data.progress.current_week||0);
  document.querySelector(`input[name="accessMode"][value="${data.access.accessMode}"]`).checked=true;
  document.querySelector('#programCalculatedWeek').textContent=data.access.status==='paused'?'Kunde pausiert · kein Wochenzugriff':`Aktuell zugänglich: ${data.access.unlockedWeeks.length?data.access.unlockedWeeks.map(week=>`W${week}`).join(', '):'keine Woche'}`;
  document.querySelector('#programAccessBadge').textContent=accessModeLabel(data.access.accessMode);
  document.querySelector('#weekOverrides').innerHTML=data.access.weekStates.map(state=>`<div class="week-override"><div><strong>Woche ${state.week}</strong><i class="${state.accessible?'open':'closed'}">${state.accessible?'zugänglich':'gesperrt'}</i></div><select data-week-override="${state.week}"><option value="auto" ${!state.adminOverride?'selected':''}>Automatisch</option><option value="unlocked" ${state.adminOverride==='unlocked'?'selected':''}>Manuell frei</option><option value="locked" ${state.adminOverride==='locked'?'selected':''}>Manuell gesperrt</option></select></div>`).join('');
  const grouped=Object.groupBy?Object.groupBy(data.gates,gate=>gate.week):data.gates.reduce((result,gate)=>{(result[gate.week]||=[]).push(gate);return result;},{});
  document.querySelector('#programGateList').innerHTML=Object.entries(grouped).map(([week,gates])=>`<div class="gate-correction-week"><strong>${Number(week)===0?'Onboarding':`Woche ${week}`}</strong>${gates.map(gate=>`<label><input type="checkbox" data-correction-gate="${gate.id}" data-original="${Boolean(gate.completed_at)}" ${gate.completed_at?'checked':''}> ${escapeHtml(gate.label)}</label>`).join('')}</div>`).join('');
  const confirmations=data.technicalConfirmations||[];
  const reached=confirmations.filter(item=>item.status!=='not_reached');
  document.querySelector('#technicalConfirmationList').innerHTML=reached.length?reached.map(item=>item.status==='confirmed'
    ?`<article class="technical-confirmation confirmed"><div><span>Woche ${item.week}</span><strong>✓ ${escapeHtml(item.title)}</strong><small>Bestätigt ${item.confirmation?.confirmedAt?new Date(item.confirmation.confirmedAt).toLocaleString('de-DE'):''}</small></div>${item.confirmation?.resultReference?`<p>Referenz: ${escapeHtml(item.confirmation.resultReference)}</p>`:''}</article>`
    :`<article class="technical-confirmation pending" data-technical-card><div><span>Woche ${item.week} · wartet auf Admin-Prüfung</span><strong>${escapeHtml(item.title)}</strong><small>Der Kunde kann diesen Schritt nicht selbst freischalten.</small></div><label>Ergebnis / Referenz<input data-technical-reference placeholder="z. B. Bericht-ID, Termin oder Ablageort"></label><label>Prüfvermerk<textarea data-technical-note rows="3" placeholder="Was wurde geprüft und bestätigt?"></textarea></label><button type="button" class="primary" data-confirm-technical data-week="${item.week}" data-step-id="${escapeHtml(item.stepId)}">Geprüft und sicher bestätigen</button></article>`).join('')
    :'<div class="technical-empty">Aktuell wartet kein externer Journey-Schritt auf eine Admin-Bestätigung.</div>';
}

document.querySelector('#technicalConfirmationList').addEventListener('click',async event=>{
  const button=event.target.closest('[data-confirm-technical]');
  if(!button)return;
  const card=button.closest('[data-technical-card]');
  const note=card.querySelector('[data-technical-note]').value.trim();
  const resultReference=card.querySelector('[data-technical-reference]').value.trim();
  if(note.length<5)return toast('Bitte einen nachvollziehbaren Prüfvermerk eingeben.');
  if(!confirm(`Technisches Ergebnis „${card.querySelector('strong').textContent}“ verbindlich bestätigen?`))return;
  button.disabled=true;
  try{
    const response=await fetch('/api/program-control',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({participantId:document.querySelector('#programParticipantId').value,technicalConfirmation:{week:Number(button.dataset.week),stepId:button.dataset.stepId,note,resultReference}})});
    const data=await response.json();
    if(!response.ok)throw new Error(data.error);
    renderProgramControl(data);
    toast('Technisches Ergebnis wurde auditierbar bestätigt.');
    await loadParticipants();
  }catch(error){toast(error.message);button.disabled=false;}
});
async function openProgramControl(participantId){if(!participantId||participantId.startsWith('demo-'))return toast('Demo-Datensatz besitzt keine serverseitige Programmsteuerung.');programDialog.showModal();document.querySelector('#programParticipantName').textContent='Wird geladen …';try{const response=await fetch(`/api/program-control?participantId=${encodeURIComponent(participantId)}`);const data=await response.json();if(!response.ok)throw new Error(data.error);renderProgramControl(data);}catch(error){programDialog.close();toast(error.message);}}
document.querySelector('#unlockAllWeeks').addEventListener('click',()=>document.querySelectorAll('[data-week-override]').forEach(select=>select.value='unlocked'));
document.querySelector('#clearWeekOverrides').addEventListener('click',()=>document.querySelectorAll('[data-week-override]').forEach(select=>select.value='auto'));
document.querySelector('#resetParticipantToOnboarding').addEventListener('click',async()=>{const id=document.querySelector('#programParticipantId').value;if(!id)return;if(!confirm('Möchtest du diesen Kunden wirklich auf den Onboarding-Start zurücksetzen?'))return;try{const response=await fetch('/api/program-control',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({participantId:id,resetToOnboarding:true})});const data=await response.json();if(!response.ok)throw new Error(data.error);renderProgramControl(data);programDialog.close();toast('Kunde wurde auf Onboarding zurückgesetzt.');await loadParticipants();}catch(error){toast(error.message);}});
document.querySelector('#programForm').addEventListener('submit',async event=>{event.preventDefault();const button=document.querySelector('#saveProgram');button.disabled=true;const overrides=[...document.querySelectorAll('[data-week-override]')];const manuallyUnlockedWeeks=overrides.filter(select=>select.value==='unlocked').map(select=>Number(select.dataset.weekOverride));const manuallyLockedWeeks=overrides.filter(select=>select.value==='locked').map(select=>Number(select.dataset.weekOverride));const gateUpdates=[...document.querySelectorAll('[data-correction-gate]')].filter(input=>String(input.checked)!==input.dataset.original).map(input=>({gateId:input.dataset.correctionGate,completed:input.checked}));const payload={participantId:document.querySelector('#programParticipantId').value,programStartDate:document.querySelector('#programStartDate').value,programStatus:document.querySelector('#programStatus').value,currentWeek:Number(document.querySelector('#programCurrentWeek').value),accessMode:document.querySelector('input[name="accessMode"]:checked').value,manuallyUnlockedWeeks,manuallyLockedWeeks,gateUpdates};try{const response=await fetch('/api/program-control',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error);renderProgramControl(data);programDialog.close();toast('Programmsteuerung wurde gespeichert.');await loadParticipants();}catch(error){toast(error.message);}finally{button.disabled=false;}});

async function loadParticipants(){try{const response=await fetch('/api/participants');const data=await response.json();if(!response.ok)throw new Error(data.error);participants=data.participants.map(p=>{const progress=p.participant_progress?.[0]||{};const parts=p.name.split(' ');return{id:p.id,name:p.name,email:p.email,week:progress.current_week||0,status:progress.process_status||'ONBOARDING',programStatus:progress.program_status||p.status,accessMode:progress.access_mode||'completion_based',startDate:progress.program_start_date||null,lastActivity:progress.last_activity_at||null,progress:Math.round((progress.current_week||0)/8*100),clarity:'—',next:'Programmsteuerung',initials:`${parts[0]?.[0]||''}${parts.at(-1)?.[0]||''}`};});}catch(error){toast(error.message);}renderParticipants();}
let bookingSettingsSnapshot=null;
const bookingDays=[['1','Montag'],['2','Dienstag'],['3','Mittwoch'],['4','Donnerstag'],['5','Freitag'],['6','Samstag'],['0','Sonntag']];
const bookingSettingsDialog=document.querySelector('#bookingSettingsDialog'),bookingSettingsForm=document.querySelector('#bookingSettingsForm');
const browserDateKey=(date=new Date())=>{const shifted=new Date(date.getTime()-date.getTimezoneOffset()*60000);return shifted.toISOString().slice(0,10);};
function addDateDays(dateKey,days){const date=new Date(`${dateKey}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10);}
function renderBookingSettings(settings){bookingSettingsSnapshot=settings;const enabledDays=bookingDays.filter(([day])=>settings.weeklyAvailability?.[day]?.length).map(([,label])=>label.slice(0,2));document.querySelector('#bookingDaysSummary').textContent=enabledDays.length?enabledDays.join(', '):'Keine';document.querySelector('#bookingDurationSummary').textContent=`${settings.defaultDurationMinutes} Min.`;document.querySelector('#bookingNoticeSummary').textContent=`${settings.minNoticeHours} Std.`;document.querySelector('#bookingHorizonSummary').textContent=`${settings.bookingHorizonDays} Tage`;const status=document.querySelector('#bookingConfigStatus');status.textContent=enabledDays.length?'Konfiguriert':'Noch nicht eingerichtet';status.classList.toggle('active',Boolean(enabledDays.length));document.querySelector('#weeklyAvailabilityRows').innerHTML=bookingDays.map(([day,label])=>{const window=settings.weeklyAvailability?.[day]?.[0],enabled=Boolean(window);return `<div class="availability-day ${enabled?'enabled':''}" data-availability-day="${day}"><label class="day-toggle"><input type="checkbox" ${enabled?'checked':''}> <b>${label}</b></label><label>von<input type="time" data-availability-start value="${window?.start||'09:00'}" ${enabled?'':'disabled'}></label><label>bis<input type="time" data-availability-end value="${window?.end||'17:00'}" ${enabled?'':'disabled'}></label></div>`;}).join('');bookingSettingsForm.elements.defaultDurationMinutes.value=String(settings.defaultDurationMinutes);bookingSettingsForm.elements.slotIntervalMinutes.value=String(settings.slotIntervalMinutes);bookingSettingsForm.elements.minNoticeHours.value=String(settings.minNoticeHours);bookingSettingsForm.elements.bookingHorizonDays.value=String(settings.bookingHorizonDays);document.querySelectorAll('[data-availability-day] .day-toggle input').forEach(input=>input.addEventListener('change',()=>{const row=input.closest('[data-availability-day]');row.classList.toggle('enabled',input.checked);row.querySelectorAll('input[type="time"]').forEach(field=>field.disabled=!input.checked);}));}
async function loadBookingSettings(){const response=await fetch('/api/leads?action=booking-settings'),data=await response.json();if(!response.ok)throw new Error(data.error);renderBookingSettings(data.settings);return data.settings;}
document.querySelector('#bookingSettings').addEventListener('click',async()=>{bookingSettingsDialog.showModal();try{await loadBookingSettings();}catch(error){bookingSettingsDialog.close();toast(error.message);}});
document.querySelectorAll('[data-close-booking-settings]').forEach(button=>button.addEventListener('click',()=>bookingSettingsDialog.close()));
bookingSettingsForm.addEventListener('submit',async event=>{event.preventDefault();const weeklyAvailability={0:[],1:[],2:[],3:[],4:[],5:[],6:[]};document.querySelectorAll('[data-availability-day]').forEach(row=>{if(row.querySelector('.day-toggle input').checked)weeklyAvailability[row.dataset.availabilityDay]=[{start:row.querySelector('[data-availability-start]').value,end:row.querySelector('[data-availability-end]').value}];});const payload={weeklyAvailability,defaultDurationMinutes:Number(bookingSettingsForm.elements.defaultDurationMinutes.value),slotIntervalMinutes:Number(bookingSettingsForm.elements.slotIntervalMinutes.value),minNoticeHours:Number(bookingSettingsForm.elements.minNoticeHours.value),bookingHorizonDays:Number(bookingSettingsForm.elements.bookingHorizonDays.value)};const button=bookingSettingsForm.querySelector('[type="submit"]');button.disabled=true;try{const response=await fetch('/api/leads?action=booking-settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw new Error(data.error);bookingSettingsSnapshot=data.settings;bookingSettingsDialog.close();toast('Verfügbarkeit wurde gespeichert.');if(leadDialog.open){leadForm.elements.appointmentDuration.value=String(data.settings.defaultDurationMinutes);await loadAvailableSlots();}}catch(error){toast(error.message);}finally{button.disabled=false;}});
const leadStatusLabels={new:'Neu',contacted:'Kontaktiert',scheduled:'Termin vereinbart',consultation:'Gespräch geführt',offer:'Angebot offen',customer:'Kunde',lost:'Nicht passend'};
const leadDialog=document.querySelector('#leadDialog'),leadForm=document.querySelector('#leadForm');
document.querySelectorAll('[data-close-lead]').forEach(button=>button.addEventListener('click',()=>leadDialog.close()));
function splitLeadName(lead){if(lead.first_name||lead.last_name)return[lead.first_name||'',lead.last_name||''];const parts=(lead.name||'').trim().split(/\s+/);return[parts.shift()||'',parts.join(' ')];}
function showSelectedSlot(iso){const selected=document.querySelector('#selectedSlot');if(!iso){selected.textContent='Noch keinen freien Termin ausgewählt';selected.classList.remove('chosen');return;}const date=new Date(iso);selected.textContent=`Ausgewählt: ${date.toLocaleString('de-DE',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})} Uhr`;selected.classList.add('chosen');}
async function loadAvailableSlots(){const container=document.querySelector('#availableSlots'),from=document.querySelector('#slotRangeStart').value||browserDateKey(),duration=Number(leadForm.elements.appointmentDuration.value);document.querySelector('#slotRangeStart').value=from;container.innerHTML='<p>Google Calendar wird auf freie Zeiten geprüft …</p>';try{const response=await fetch(`/api/leads?action=available-slots&from=${encodeURIComponent(from)}&to=${encodeURIComponent(addDateDays(from,13))}&duration=${duration}`),data=await response.json();if(!response.ok)throw new Error(data.error);bookingSettingsSnapshot=data.settings;if(!data.slots.length){container.innerHTML='<p>In diesem Zeitraum gibt es keine freigegebenen freien Termine. Passe den Zeitraum oder deine Verfügbarkeit an.</p>';return;}const groups=data.slots.reduce((result,slot)=>{(result[slot.date]||=[]).push(slot);return result;},{});container.innerHTML=Object.entries(groups).map(([date,slots])=>`<article><strong>${new Date(`${date}T12:00:00`).toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'2-digit'})}</strong><div>${slots.map(slot=>`<button type="button" data-slot-start="${escapeHtml(slot.start)}">${escapeHtml(slot.time)} Uhr</button>`).join('')}</div></article>`).join('');container.querySelectorAll('[data-slot-start]').forEach(button=>button.addEventListener('click',()=>{leadForm.elements.appointmentStart.value=button.dataset.slotStart;container.querySelectorAll('[data-slot-start]').forEach(item=>item.classList.toggle('selected',item===button));showSelectedSlot(button.dataset.slotStart);}));}catch(error){container.innerHTML=`<p>${escapeHtml(error.message)}</p>`;}}
function leadPayload(){const values=Object.fromEntries(new FormData(leadForm));return{id:values.id,firstName:values.firstName,lastName:values.lastName,email:values.email,phone:values.phone,status:values.status,challenge:values.challenge,internalNotes:values.internalNotes,qualificationAnswers:Object.fromEntries(Array.from({length:6},(_,index)=>[`q${index+1}`,values[`q${index+1}`]||'']))};}
function updateLeadCache(lead){const index=leads.findIndex(item=>item.id===lead.id);if(index>=0)leads[index]=lead;else leads.unshift(lead);}
function renderLeadDialog(lead){const[firstName,lastName]=splitLeadName(lead),answers=lead.qualification_answers||{};leadForm.elements.id.value=lead.id;leadForm.elements.firstName.value=firstName;leadForm.elements.lastName.value=lastName;leadForm.elements.email.value=lead.email||'';leadForm.elements.phone.value=lead.phone||'';leadForm.elements.status.value=lead.status||'new';leadForm.elements.challenge.value=lead.challenge||'';leadForm.elements.internalNotes.value=lead.internal_notes||'';for(let index=1;index<=6;index+=1)leadForm.elements[`q${index}`].value=answers[`q${index}`]||'';document.querySelector('#leadDialogTitle').textContent=lead.name;document.querySelector('#leadDialogSource').textContent=`${lead.utm_source||lead.source||'unbekannt'} · eingegangen ${new Date(lead.created_at).toLocaleDateString('de-DE')}`;leadForm.elements.appointmentStart.value=lead.appointment_start||'';if(lead.appointment_start&&lead.appointment_end)leadForm.elements.appointmentDuration.value=String(Math.round((new Date(lead.appointment_end)-new Date(lead.appointment_start))/60000));else if(bookingSettingsSnapshot)leadForm.elements.appointmentDuration.value=String(bookingSettingsSnapshot.defaultDurationMinutes);showSelectedSlot(lead.appointment_start);document.querySelector('#leadAppointmentState').textContent=lead.appointment_start?new Date(lead.appointment_start).toLocaleString('de-DE',{dateStyle:'medium',timeStyle:'short'}):'Noch kein Termin';const meet=document.querySelector('#openMeet'),calendar=document.querySelector('#openCalendarEvent'),cancel=document.querySelector('#cancelLeadAppointment');meet.classList.toggle('hidden',!lead.meet_url);calendar.classList.toggle('hidden',!lead.calendar_event_url);cancel.classList.toggle('hidden',!lead.calendar_event_id);if(lead.meet_url)meet.href=lead.meet_url;if(lead.calendar_event_url)calendar.href=lead.calendar_event_url;document.querySelector('#leadConversionState').textContent=lead.converted_user_profile_id?'Kundenkonto wurde angelegt':'Noch kein Konto angelegt';document.querySelector('#convertLead').disabled=Boolean(lead.converted_user_profile_id);leadForm.elements.programStartDate.value=new Date().toISOString().slice(0,10);}
async function openLead(id){const lead=leads.find(item=>item.id===id);if(!lead)return;document.querySelector('#slotRangeStart').value=browserDateKey();renderLeadDialog(lead);leadDialog.showModal();await loadAvailableSlots();}
async function saveLead(showMessage=true){const response=await fetch('/api/leads?action=update',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(leadPayload())});const data=await response.json();if(!response.ok)throw new Error(data.error);updateLeadCache(data.lead);renderLeadDialog(data.lead);if(showMessage)toast('Interessent wurde gespeichert.');return data.lead;}
leadForm.addEventListener('submit',async event=>{event.preventDefault();try{await saveLead();await loadLeads();}catch(error){toast(error.message);}});
document.querySelector('#refreshSlots').addEventListener('click',loadAvailableSlots);
document.querySelector('#slotRangeStart').addEventListener('change',loadAvailableSlots);
leadForm.elements.appointmentDuration.addEventListener('change',()=>{leadForm.elements.appointmentStart.value='';showSelectedSlot('');loadAvailableSlots();});
document.querySelector('#scheduleLead').addEventListener('click',async()=>{const button=document.querySelector('#scheduleLead'),start=leadForm.elements.appointmentStart.value,duration=Number(leadForm.elements.appointmentDuration.value);if(!start)return toast('Bitte einen angezeigten freien Termin auswählen.');button.disabled=true;try{const saved=await saveLead(false);const response=await fetch('/api/leads?action=schedule',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:saved.id,start:new Date(start).toISOString(),duration})});const data=await response.json();if(!response.ok)throw new Error(data.error);updateLeadCache(data.lead);renderLeadDialog(data.lead);toast('Kalendertermin und Google Meet wurden erstellt.');await loadLeads();}catch(error){toast(error.message);}finally{button.disabled=false;}});
document.querySelector('#cancelLeadAppointment').addEventListener('click',async()=>{if(!confirm('Termin wirklich absagen? Google informiert den eingeladenen Interessenten.'))return;try{const response=await fetch('/api/leads?action=cancel-appointment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:leadForm.elements.id.value})});const data=await response.json();if(!response.ok)throw new Error(data.error);updateLeadCache(data.lead);renderLeadDialog(data.lead);toast('Termin wurde abgesagt.');await loadLeads();}catch(error){toast(error.message);}});
document.querySelector('#convertLead').addEventListener('click',async()=>{if(!confirm('Kauf bestätigen und dem Kunden jetzt die E-Mail zur Passwortvergabe senden?'))return;const button=document.querySelector('#convertLead');button.disabled=true;try{const saved=await saveLead(false);const permissions=[...leadForm.querySelectorAll('[name="leadPermissions"]:checked')].map(input=>input.value);const response=await fetch('/api/leads?action=convert',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:saved.id,firstName:leadForm.elements.firstName.value,lastName:leadForm.elements.lastName.value,email:leadForm.elements.email.value,programStartDate:leadForm.elements.programStartDate.value,permissions})});const data=await response.json();if(!response.ok)throw new Error(data.error);updateLeadCache(data.lead);renderLeadDialog(data.lead);toast('Kundenkonto aktiviert und Einladungsmail versendet.');await Promise.all([loadLeads(),loadParticipants(),loadUsers()]);}catch(error){toast(error.message);button.disabled=false;}});
document.querySelector('#googleConnect').addEventListener('click',()=>{location.href='/api/google/connect';});
async function loadGoogleStatus(){try{const response=await fetch('/api/leads?action=google-status'),data=await response.json();if(!response.ok)throw new Error(data.error);document.querySelector('#googleStatus').textContent=data.connected?`● Verbunden: ${data.email||'Google Calendar'}`:data.configured?'Noch nicht mit Google verbunden':'Google-Zugangsdaten fehlen';document.querySelector('#googleConnect').textContent=data.connected?'Google neu verbinden':'Google Calendar verbinden';}catch(error){document.querySelector('#googleStatus').textContent=error.message;}}
async function loadLeads(){try{const response=await fetch('/api/leads');const data=await response.json();if(!response.ok)throw new Error(data.error);leads=data.leads;document.querySelector('#leadRows').innerHTML=leads.length?leads.map(lead=>`<div class="table-data lead-row" data-lead-id="${escapeHtml(lead.id)}"><div class="participant"><span class="avatar">${escapeHtml(lead.name.slice(0,2).toUpperCase())}</span><div><strong>${escapeHtml(lead.name)}</strong><small>${escapeHtml(lead.email)}</small></div></div><span>${escapeHtml(lead.utm_source||lead.source)}</span><span>${escapeHtml(leadStatusLabels[lead.status]||lead.status)}</span><span>${new Date(lead.created_at).toLocaleDateString('de-DE')}</span><button class="lead-next" data-open-lead="${escapeHtml(lead.id)}">${lead.appointment_start?`${new Date(lead.appointment_start).toLocaleDateString('de-DE')} · ${new Date(lead.appointment_start).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}`:'Bearbeiten →'}</button></div>`).join(''):'<div class="empty">Noch keine Interessenten vorhanden.</div>';document.querySelectorAll('[data-open-lead]').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();openLead(button.dataset.openLead);}));document.querySelectorAll('.lead-row').forEach(row=>row.addEventListener('click',()=>openLead(row.dataset.leadId)));}catch(error){document.querySelector('#leadRows').innerHTML=`<div class="empty">${escapeHtml(error.message)}</div>`;}}
async function loadUsers(){try{const response=await fetch('/api/users');const data=await response.json();if(!response.ok)throw new Error(data.error);users=data.users;const permissionLabels={customer_portal:'Kundenportal',clara_program:'Clara',documents:'Dokumente',community:'Community'};document.querySelector('#userRows').innerHTML=users.length?users.map(user=>{const progress=user.participant_progress?.[0];return `<div class="table-data"><div class="participant"><span class="avatar">${escapeHtml(user.name.slice(0,2).toUpperCase())}</span><div><strong>${escapeHtml(user.name)}</strong><small>${escapeHtml(user.email)}</small></div></div><span class="user-meta"><b>${user.role==='admin'?'Admin':'Benutzer'}</b><small>${user.status==='active'?'Aktiv':'Deaktiviert'}</small></span><span class="access-tags">${user.role==='admin'?'<i>Alle Rechte</i>':(user.permissions||[]).map(permission=>`<i>${escapeHtml(permissionLabels[permission]||permission)}</i>`).join('')||'<i>Keine Zugänge</i>'}</span><span class="user-meta"><b>${progress?`Woche ${progress.current_week}`:'—'}</b><small>${escapeHtml(progress?.program_status||'Kein Programm')}</small></span><button class="user-manage" data-edit-user="${escapeHtml(user.id)}">Bearbeiten →</button></div>`;}).join(''):'<div class="empty">Noch keine Benutzer vorhanden.</div>';document.querySelectorAll('[data-edit-user]').forEach(button=>button.addEventListener('click',()=>openUserEdit(button.dataset.editUser)));}catch(error){document.querySelector('#userRows').innerHTML=`<div class="empty">${escapeHtml(error.message)}</div>`;}}
document.querySelector('#logout').addEventListener('click',async()=>{await fetch('/api/auth?action=session',{method:'DELETE'});location.replace('/login');});
const adminParams=new URLSearchParams(location.search);if(adminParams.get('view')&&titles[adminParams.get('view')])showView(adminParams.get('view'));if(adminParams.get('section'))showSettingsPanel(adminParams.get('section'));if(adminParams.get('google')==='connected')toast('Google Calendar wurde erfolgreich verbunden.');else if(adminParams.get('google')==='error')toast('Google-Verbindung wurde abgebrochen.');if(location.search)history.replaceState(null,'',location.pathname);
fetch('/api/auth?action=session').then(response=>{if(!response.ok)location.replace('/login');else Promise.all([loadParticipants(),loadLeads(),loadUsers(),loadGoogleStatus(),loadBookingSettings().catch(error=>toast(error.message))]);});renderParticipants();
