const duration=Number(new URLSearchParams(location.search).get('dauer'));
const message=document.querySelector('#message'),slots=document.querySelector('#slots'),form=document.querySelector('#form');
let selected=null;
const dayKey=offset=>{const date=new Date();date.setDate(date.getDate()+offset);return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(date)};
const label=value=>new Intl.DateTimeFormat('de-DE',{timeZone:'Europe/Berlin',weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
if(![15,30,45,60].includes(duration)){message.textContent='Dieser Buchungslink ist ungültig.';}else{
  document.querySelector('#title').textContent=`Q&A Gespräch · ${duration} Minuten`;
  fetch(`/api/leads?action=public-qa-slots&duration=${duration}&from=${dayKey(0)}&to=${dayKey(21)}`).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error||'Termine konnten nicht geladen werden.');if(!data.calendarConnected)throw Error('Der Google-Kalender ist derzeit nicht verfügbar.');message.textContent=data.slots.length?'Wähle einen freien Termin:':'Derzeit sind keine freien Termine vorhanden.';slots.innerHTML='';for(const slot of data.slots){const button=document.createElement('button');button.type='button';button.className='slot';button.innerHTML=`<strong>${label(slot.start)}</strong><small>${duration} Minuten</small>`;button.addEventListener('click',()=>{selected=slot.start;slots.querySelectorAll('.slot').forEach(item=>item.classList.toggle('selected',item===button));form.hidden=false;message.textContent=`Ausgewählter Termin: ${label(selected)} Uhr`;});slots.append(button);}}).catch(error=>{message.textContent=error.message;});
  form.addEventListener('submit',async event=>{event.preventDefault();if(!selected)return;const button=form.querySelector('[type="submit"]');button.disabled=true;message.textContent='Termin wird gebucht …';try{const payload=Object.fromEntries(new FormData(form));payload.start=selected;payload.duration=duration;const response=await fetch('/api/leads?action=public-qa-book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw Error(data.error||'Buchung fehlgeschlagen.');slots.hidden=true;form.hidden=true;message.innerHTML=`Dein Q&A Gespräch am ${label(data.start)} Uhr ist gebucht. ${data.mailStatus==='accepted'?'Die Bestätigung wurde per E-Mail verschickt. Bitte prüfe auch den Spam-Ordner.':'Die E-Mail-Bestätigung konnte noch nicht verschickt werden.'} <a href="${data.meetUrl}" target="_blank" rel="noopener">Google Meet öffnen ↗</a>`;}catch(error){message.textContent=error.message;button.disabled=false;}});
}
