const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
import {readFile} from 'node:fs/promises';import path from 'node:path';import {pathToFileURL} from 'node:url';
const base=process.cwd();const {createWeekOneState}=await import(pathToFileURL(path.join(base,'lib/week-one.js')));const {calculateProgramAccess,serializeProgramAccess,reconcileProgramPosition}=await import(pathToFileURL(path.join(base,'lib/program-access.js')));
const definition=JSON.parse(await readFile('curriculum/fdd-4plus4.json','utf8'));const weekOne=createWeekOneState();weekOne.clarity_baseline={score:3,completed:true};
const progress={privacy_consent_at:'2026-09-01',start_commitment_at:'2026-09-01',program_start_date:'2026-09-01',program_status:'active',current_week:1,process_status:'WEEK_1'};const access=serializeProgramAccess(reconcileProgramPosition(calculateProgramAccess({progress,fullProgramAccess:true}),[]));
const data={profile:{id:'demo',name:'Curriculum Test',email:'test@example.test',programInsights:{motivators:[]}},onboarding:{privacyConfirmed:true,commitmentConfirmed:true,commitmentUploaded:true,profileComplete:true,missingProfileFields:[],formDrafts:{}},onboardingComplete:true,access,processVersion:{version:1,definition},curriculum:[],programWeeks:definition.weeks.map((w,i)=>({week:i+1,title:w.title,mode:w.mode,description:w.intro,topics:w.steps.map(s=>s.title)})),accessibleWeeks:definition.weeks.map((w,i)=>({week:i+1,title:w.title,mode:w.mode})),selectedWeek:1,week:{week:1,title:definition.weeks[0].title,mode:definition.weeks[0].mode,tasks:[],questions:[]},weekOne,weekOneGate:{complete:false,missingRequirements:[]},weekState:null,weekGate:null,weekDraft:{},weekReflections:[],clarityHistory:[{week:1,score:3}],currentClarity:{score:3},clarityTimeline:[]};
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.stack));
await page.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname!=='preview.test')return r.abort();if(u.pathname.startsWith('/api/')){if(u.pathname==='/api/participant-program')return r.fulfill({json:u.searchParams.get('feature')==='login-clarity'?{required:false,history:[]}:data});return r.fulfill({json:{documents:[],communications:[],appointments:[],profile:{},user:{role:'user',name:'Test'}}});}try{const file=path.join(base,u.pathname==='/portal'?'/portal.html':u.pathname);return r.fulfill({body:await readFile(file),contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'});}catch{return r.fulfill({status:404,body:''});}});
await page.goto('https://preview.test/portal');await page.locator('#openCurrentWeek').waitFor({state:'visible'});await page.locator('#openCurrentWeek').click();await page.locator('#curriculumAnswer textarea').waitFor({state:'visible'});await page.screenshot({path:'/tmp/curriculum-full-portal.png',fullPage:true});if(errors.length)throw Error(errors.join('\n'));await page.setViewportSize({width:390,height:844});await page.locator('#closeMobileProcess').click({timeout:1000}).catch(()=>{});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Portal mobile overflow');console.log('PASS full existing portal loads 4+4, dashboard start works and mobile has no overflow');await browser.close();
