export const CURRICULUM_METHODS=Object.freeze({
 evidence_dialog:{title:'Beleggestützter Dialog',learningGoal:'Eine persönliche Aussage anhand konkreter Erfahrungen nachvollziehbar vertiefen.',opening:'Welche konkrete Erfahrung möchtest du genauer verstehen?',question:'Was ist passiert, was hast du getan und was bedeutet dir das?',adaptiveLogic:'Bei Verallgemeinerungen nach einer konkreten Situation fragen. Eigene Deutungen als Hypothese spiegeln und bestätigen lassen.',storageLogic:'Originalaussage, Situation, Verhalten, Bedürfnis, Ableitung, Gegenbeleg und Teilnehmerstatus getrennt speichern.',evaluation:'Kurze belegte Zusammenfassung mit offener Bestätigungsfrage.'},
 matrix:{title:'Vergleichsmatrix',learningGoal:'Mehrere Dimensionen mit konkreten Präferenzen und Belegen vergleichen.',opening:'Wir sortieren die Bedingungen, unter denen es für dich gut funktioniert.',question:'Welche Dimensionen sind wichtig? Was brauchst du, was nicht und woher weißt du das?',adaptiveLogic:'Eine Dimension nach der anderen. Widersprüchliche Wünsche nebeneinander erhalten, nicht zu einem Mittelwert glätten.',storageLogic:'Matrix mit Dimension, bevorzugter Ausprägung, No-Go, konkretem Beleg und Priorität.',evaluation:'Must-haves, verhandelbare Bedingungen und offene Spannungen.'},
 timeline:{title:'Entscheidungs-Timeline',learningGoal:'Prägende Entscheidungen und Fremdeinflüsse über den Lebensverlauf erkennen.',opening:'Welche Entscheidungen haben deinen Weg besonders geprägt?',question:'Wann war das? Was stand zur Wahl? Warum hast du dich so entschieden und was folgte daraus?',adaptiveLogic:'Entscheidungen statt vollständiger Lebenslaufdaten erheben. Eigene Motivation und äußere Erwartung unterscheiden.',storageLogic:'Chronologische Einträge: Zeitraum, Entscheidung, Alternativen, eigener Antrieb, Fremdeinfluss, Folge und heutige Bewertung.',evaluation:'Vorläufige wiederkehrende Entscheidungsweisen mit Ursprungsquellen.'},
 research:{title:'Recherche mit Quellen',learningGoal:'Annahmen mit nachvollziehbaren Außenweltdaten prüfen.',opening:'Welche Frage musst du außerhalb dieses Gesprächs prüfen?',question:'Welche Quelle oder welches Gespräch hilft? Was hast du dort konkret erfahren?',adaptiveLogic:'Ungeprüfte Informationen kennzeichnen. Quellen nicht erfinden. Recherche von persönlicher Vermutung unterscheiden.',storageLogic:'Forschungsfrage, Quelle oder Gesprächspartner, Datum, Fundstelle, Originalbeobachtung, Interpretation und offene Frage.',evaluation:'Was ist belegt, was bleibt unklar und welcher Praxistest folgt?'},
 hypothesis:{title:'Hypothesenprüfung',learningGoal:'Eine Annahme prüfbar formulieren und Gegenbelege sichtbar machen.',opening:'Welche Annahme entscheidet darüber, ob diese Richtung passt?',question:'Was vermutest du? Was spricht dafür oder dagegen? Welches Ergebnis würde deine Annahme verändern?',adaptiveLogic:'Keine Bestätigungsfragen stellen. Person, Alltag, Markt, Fähigkeit und Rahmen getrennt betrachten.',storageLogic:'Hypothese, Kategorie, Wichtigkeit, Ursprungsquellen, Gegenbelege, Testidee und Teilnehmerstatus.',evaluation:'Priorisierte Liste der noch zu prüfenden Annahmen.'},
 proof:{title:'Proof Sprint',learningGoal:'Eine kritische Annahme mit einer kleinen echten Handlung prüfen.',opening:'Welcher kleine reale Test bringt dir jetzt neue Erkenntnisse?',question:'Was tust du, mit wem und bis wann? Was beobachtest du und was würde deine Annahme widerlegen?',adaptiveLogic:'Passende Testform wählen: Informationsgespräch, Hospitation, kleine Arbeitsprobe, Angebotstest oder eigenständiges Mini-Projekt. Recherche allein reicht nicht, wenn echte Interaktion möglich ist. Bei Terminabhängigkeit einen selbst steuerbaren zweiten Weg wählen.',storageLogic:'Testform, Hypothese, Handlung, Kontakt, Starttermin, Lernkriterium, Unterstützung, rohe Beobachtung, Ergebnis und Gegenbelege.',evaluation:'Bestätigt, widerlegt oder offen. Beobachtung vor Interpretation; negative Tests sind Erkenntnisse.'},
 action_plan:{title:'Aktionsplan',learningGoal:'Ein selbst steuerbares Ziel in konkrete Schritte übersetzen.',opening:'Was soll sich in den nächsten 90 Tagen konkret verändern?',question:'Was ist dein Hauptziel? Welche drei Meilensteine helfen? Was tust du in den ersten 72 Stunden?',adaptiveLogic:'Ergebnisse von Aktivitäten unterscheiden. Ressourcen, Risiken, Plan B und einen konkreten Review-Termin klären.',storageLogic:'Hauptziel, drei Meilensteine, Backlog, Verantwortliche, Termine, Unterstützer, Risiken, Plan B, erster 72-Stunden-Schritt und Review-Termin.',evaluation:'Umsetzbarer Plan mit einem sichtbaren nächsten Schritt.'},
 synthesis:{title:'Synthese mit Bestätigung',learningGoal:'Bisherige Angaben nachvollziehbar verdichten und persönlich überprüfen.',opening:'Lass uns prüfen, welches Bild aus deinen bisherigen Angaben entsteht.',question:'Was trifft zu, was nur teilweise und was möchtest du korrigieren?',adaptiveLogic:'Originalquellen referenzieren. Zusammenfassungen erzeugen keine neuen unabhängigen Belege. Gegenbelege erhalten und unklare Punkte offen lassen.',storageLogic:'Zusammenfassung, Kernmuster, Ursprungsquellen, Gegenbelege, Teilnehmerstatus, offene Fragen und nächster Impuls.',evaluation:'Ergebnis zur ausdrücklichen Bestätigung vorlegen, kein fertiges Etikett erzwingen.'},
});
