import {CURRICULUM_METHODS} from './curriculum-methods.js';
import OpenAI from 'openai';
import {claraConfig} from './clara/config.js';
export const isCurriculum=definition=>definition?.engine==='curriculum_4plus4';
export const curriculumMethods=['evidence_dialog','matrix','timeline','research','hypothesis','proof','action_plan','synthesis'];
export function evidenceStrength(signal){const count=new Set(signal.source_ids||[]).size;if(['widersprochen','abgeschwächt'].includes(signal.participant_status)||signal.model_only||signal.counter_evidence?.length)return 'schwach';if(count>=3&&signal.participant_status==='bestätigt')return signal.real_test?'sehr stark':'stark';return count>=2?'mittel':'schwach';}
export function normalizeSignals(signals, sources) {
 const byId=new Map(sources.map(s=>[s.id,s]));
 return (Array.isArray(signals)?signals:[]).slice(0,30).map(s=>{
  const known=[...new Set(Array.isArray(s.source_ids)?s.source_ids:[])].map(id=>byId.get(id)).filter(Boolean);
  const distinctText=[...new Map(known.filter(source=>!source.optionalModel&&!source.synthesis).map(source=>[String(source.text).trim().replace(/\s+/g,' ').toLocaleLowerCase('de'),source])).values()];
  const independent=[...new Map(distinctText.map(source=>[source.lesson,source])).values()];
  const value={signal:String(s.signal||'').slice(0,300),source_ids:independent.map(source=>source.id),original_evidence:independent.map(source=>source.text).join('\n').slice(0,6000),inference:String(s.inference||'').slice(0,2000),participant_status:'offen',counter_evidence:(Array.isArray(s.counter_evidence)?s.counter_evidence:[]).map(String).slice(0,10),phase:String(s.phase||'Gegenwart').slice(0,100),model_only:!independent.length || Boolean(s.model_only) || independent.every(source=>source.optionalModel),real_test:Boolean(s.real_test)&&independent.some(source=>source.week===1)&&independent.some(source=>source.week===2)&&independent.some(source=>source.week===3)&&independent.some(source=>source.week>=7)};
  if(value.model_only)value.source_ids=[];
  return {...value,strength:evidenceStrength(value)};
 });
}
export async function curriculumQuery(service,path,method='GET',body){const r=await fetch(`${service.url}/rest/v1/${path}`,{method,headers:{apikey:service.key,Authorization:`Bearer ${service.key}`,'Content-Type':'application/json',Prefer:'return=representation'},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.message||'Curriculum konnte nicht gespeichert werden.'),{status:409});return data;}
export async function curriculumRecords(service,id,version){return curriculumQuery(service,`curriculum_lessons?user_profile_id=eq.${encodeURIComponent(id)}&version=eq.${Number(version)}&order=week.asc,updated_at.asc`);}
export const curriculumSystem=`Du bist Clara im FDD-4+4-Prozess. Sprich klar, warm und ohne Diagnosen. Folge ausschließlich der aktuellen Lektion und ihrem Lernziel, Einstieg, Kernfragen, adaptiver Logik und Speicherlogik. Stelle jeweils eine sinnvolle vertiefende Frage, keine Fragenlawine. Woche 1–3: keine Berufsdiagnose und keine suggestive Bestätigung früher Berufsideen. Woche 4: erst Rohdaten, dann Konvergenz und eine vorläufige Hypothese; zwei starke Richtungen sind besser als drei erzwungene. Woche 5–8: Vision mit beobachtbaren Außenweltdaten prüfen, echte selbst steuerbare Aktionen, kein künstlicher Zeitdruck und keine erzwungene Jobkündigung. Negative Tests sind Erkenntnisse, kein Scheitern. Unbekannte Marktfakten nicht erfinden. Recherchequellen müssen vom Teilnehmer stammen; Links sind kein Beweis, dass du sie geprüft hast. Trenne Rohbeleg und Interpretation. Mehrere Ableitungen aus derselben Aussage zählen als EINE Ursprungsquelle. Human Design ist optional, sekundär und erhöht keine empirische Evidenz. Gegenbelege und Widersprüche sichtbar erhalten; Widerspruch senkt Konfidenz. Keine stillschweigende Teilnehmerbestätigung. Gib source_ids nur aus supplied source records an. Kein Happy End erzwingen. Keine Änderung an Klarheitsscores: vorhandene Klarheitsfunktion bleibt separat. Videos vermitteln nur Kontext, du erhebst und vertiefst individuell. Bei Synthesen beziehe alle bisherigen bestätigten Lektionen ein. ready=true nur wenn die Lernziele anhand konkreter Angaben erfüllt sind; Synthesen müssen zunächst vom Teilnehmer bestätigt werden. Die Kundenansicht ist ausschließlich ein Gespräch: message enthält nur deine natürliche Antwort an den Teilnehmer. Zeige darin keine Speicherfelder, Konfidenzwerte, source_ids, technischen Prüfvermerke oder interne Prozessanweisungen. Kläre Unsicherheiten und Widersprüche durch eine verständliche Rückfrage im Dialog. Wenn ready=true, fasse das gemeinsam Erarbeitete kurz in message zusammen und bitte um Bestätigung oder Korrektur. Die interne Auswertung bleibt ausschließlich in summary, structured_data und signals. Ausgabe als JSON: {message:string,ready:boolean,summary:string,structured_data:object,signals:[{signal:string,source_ids:string[],original_evidence:string,inference:string,counter_evidence:string[],phase:string,model_only:boolean,real_test:boolean}]}. Verwende verständliche deutsche Feldbezeichnungen in structured_data. structured_data bildet genau die Speicherlogik der Lektion ab. Beobachtungen, Annahmen, Gegenbelege, No-Gos, Verantwortliche, Termine und offene Fragen getrennt halten.`;
export async function respondCurriculum({lesson,week,records,messages,sourceId,env=process.env,client}){const config=claraConfig(env);if(!config.apiKey&&!client)throw Object.assign(new Error('Claras KI-Verbindung ist noch nicht konfiguriert.'),{status:503});const ai=client||new OpenAI({apiKey:config.apiKey});const sources=records.flatMap(r=>(r.messages||[]).filter(m=>m.role==='user').map(m=>({id:m.source_id,text:m.content,lesson:r.step_id,week:r.week,optionalModel:r.step_id==='c44_w2_l5',synthesis:['c44_w1_l5','c44_w2_l6','c44_w3_l5','c44_w4_l5','c44_w5_l4','c44_w7_l4','c44_w8_l5'].includes(r.step_id)})));sources.push(...messages.filter(m=>m.role==='user').map(m=>({id:m.source_id,text:m.content,lesson:lesson.id,week,optionalModel:lesson.optional&&lesson.id==='c44_w2_l5',synthesis:lesson.method==='synthesis'})));const result=await ai.responses.create({model:config.model,store:false,max_output_tokens:4000,instructions:curriculumSystem,input:JSON.stringify({response_format:'json',week,lesson,methodInstructions:CURRICULUM_METHODS[lesson.method||'evidence_dialog'],sourceId,sources,previous:records.map(r=>({week:r.week,step:r.step_id,status:r.status,summary:r.summary,structured_data:r.structured_data,signals:r.signals})),messages}),text:{format:{type:'json_object'}}});let out;try{out=JSON.parse(result.output_text);}catch{throw new Error('Claras Antwort konnte nicht gelesen werden. Bitte erneut versuchen.');}if(typeof out.message!=='string'||typeof out.ready!=='boolean'||typeof out.summary!=='string'||!out.structured_data||typeof out.structured_data!=='object'||Array.isArray(out.structured_data))throw new Error('Claras Antwort ist unvollständig.');out.signals=normalizeSignals(out.signals,sources);return out;}

export function completedCurriculumWeeks(definition, records) { return definition.weeks.flatMap((w,i) => { const required=w.steps.filter(s=>!s.optional); return records.some(r=>r.step_id===`week_complete_${i+1}`&&r.status==='completed') && required.length && required.every(s=>records.some(r=>r.week===i+1 && r.step_id===s.id && r.status==='completed')) ? [i+1] : []; }); }
