import {cents,invoiceBalances} from './finance.js';
export const accountKinds={claim:'Forderung',payment:'Zahlung',credit:'Gutschrift',writeoff:'Ausbuchung',due:'Fälligkeit'};
export const accountStatuses={open:'Offen',partial:'Teilbezahlt',overdue:'Überfällig',paid:'Bezahlt',settled:'Ausgeglichen',credited:'Gutgeschrieben',written_off:'Ausgebucht',future:'Künftig fällig',booked:'Gebucht',unassigned:'Nicht zugeordnet',pending:'Vorgemerkt',cancelled:'Storniert'};
export function customerAccount({invoices=[],payments=[],events=[],today}){
 const balances=invoiceBalances(invoices,payments,today,events).filter(i=>i.status==='issued'&&i.invoice_date<=today);
 const byId=new Map(balances.map(i=>[i.id,i])),entries=[];
 for(const i of balances)entries.push({id:i.id,invoiceId:i.id,date:i.invoice_date,created:i.created_at||'',kind:'claim',number:i.invoice_number,description:i.description,dueDate:i.due_date,status:i.open>0&&i.due_date>today?'future':i.payment_status,amount:Number(i.gross),net:Number(i.net),vat:Number(i.vat),vatRate:Number(i.vat_rate),source:i.contract_id?'Vertrag':'Manuelle Forderung',open:i.open});
 for(const p of payments.filter(p=>p.booked_at<=today))entries.push({id:p.id,invoiceId:p.invoice_id,date:p.booked_at,created:p.created_at||'',kind:'payment',number:byId.get(p.invoice_id)?.invoice_number||'Ohne Rechnungszuordnung',description:p.reference||'Zahlungseingang',method:p.payment_method||'other',status:p.status==='booked'?(p.invoice_id?'booked':'unassigned'):p.status,amount:p.status==='booked'?-Number(p.amount):0,nominalAmount:Number(p.amount)});
 for(const e of events.filter(e=>e.booked_at<=today))entries.push({id:e.id,invoiceId:e.invoice_id,date:e.booked_at,created:e.created_at||'',kind:e.kind,number:e.document_number,description:e.reason,invoiceNumber:byId.get(e.invoice_id)?.invoice_number||'',dueDate:e.due_date,status:'booked',amount:-Number(e.amount),net:e.kind==='credit'?Number(e.net):null,vat:e.kind==='credit'?Number(e.vat):null,vatRate:e.kind==='credit'?Number(byId.get(e.invoice_id)?.vat_rate):null,actor:e.actor});
 // Stable journal order: same-day receivables precede payments and adjustments.
 entries.sort((a,b)=>a.date.localeCompare(b.date)||((a.kind==='claim'?0:1)-(b.kind==='claim'?0:1))||a.created.localeCompare(b.created)||a.id.localeCompare(b.id));
 let running=0;for(const e of entries){running+=cents(e.amount);e.balance=running/100;}
 const sum=(rows,key)=>rows.reduce((s,r)=>s+cents(r[key]),0)/100;
 const open=sum(balances,'open'),future=sum(balances.filter(i=>i.due_date>today),'open'),paid=sum(payments.filter(p=>p.status==='booked'&&p.booked_at<=today),'amount'),balance=running/100;
 return{today,entries,invoices:balances,summary:{balance,open,future,due:Math.round((open-future)*100)/100,overdue:sum(balances.filter(i=>i.due_date<today),'open'),payments:paid,credits:sum(events.filter(e=>e.kind==='credit'&&e.booked_at<=today),'amount'),writeoffs:sum(events.filter(e=>e.kind==='writeoff'&&e.booked_at<=today),'amount'),unallocated:sum(payments.filter(p=>p.status==='booked'&&!p.invoice_id&&p.booked_at<=today),'amount'),customerCredit:Math.max(0,Math.round((open-balance)*100)/100)},pendingInvoices:invoices.filter(i=>i.status==='needs_details').length};
}
