insert into public.communication_templates(template_key,name,description,category,channel,subject,body,status) values
('intake_admin_notification','Neue Anmeldung an Markus','Automatische Benachrichtigung mit Telefonnummer nach gebuchtem Intake-Termin.','lead','email','Neue Anmeldung zum Klarheitsgespräch: {{name}}',E'Hallo Markus,\n\n{{name}} hat sich über das Intake-Verfahren angemeldet und ein Klarheitsgespräch gebucht.\n\nName: {{name}}\nE-Mail: {{email}}\nTelefon: {{phone}}\nTermin: {{appointment}} Uhr\nGoogle Meet: {{meet_url}}\n\nDie Angaben und Antworten findest du in der Interessentenakte im CRM.','active'),
('intake_appointment_confirmation','Klarheitsgespräch: Terminbestätigung','Bestätigung des gebuchten Intake-Termins mit Google Meet.','appointment','email','Dein Klarheitsgespräch ist bestätigt',E'Hallo {{vorname}},\n\nvielen Dank, dass du dir Zeit für dein Klarheitsgespräch nimmst. Ich freue mich darauf, dich und deine Situation kennenzulernen.\n\nDein Termin: {{appointment}} Uhr\n\nÜber diesen Link kommst du direkt in unser Gespräch:\n{{meet_url}}\n\nWenn du den Termin verschieben musst, antworte einfach auf diese E-Mail.','active'),
('qa_appointment_confirmation','Q&A: Terminbestätigung','Bestätigung eines gebuchten Q&A-Gesprächs mit Google Meet.','appointment','email','Dein Q&A Gespräch am {{appointment}}',E'Hallo {{vorname}},\n\ndein Q&A Gespräch ist bestätigt.\n\nTermin: {{appointment}} Uhr\nDauer: {{duration}} Minuten\nGoogle Meet: {{meet_url}}\n\nWenn du den Termin verschieben musst, antworte bitte auf diese E-Mail.','active'),
('follow_up_reminder','Follow-up an Markus','Erinnerung am Fälligkeitstag eines Interessenten-Follow-ups.','lead','email','Follow-up heute: {{name}}',E'Hallo Markus,\n\nfür {{name}} steht heute ({{date}}) ein Follow-up an. Bitte kontaktiere diesen Interessenten.\n\nTelefon: {{phone}}\nE-Mail: {{email}}\n\nDie Kontaktdaten und den bisherigen Verlauf findest du in der Interessentenakte.','active'),
('stripe_payment_link','Stripe-Zahlungslink','Zahlungslink für einen offenen Betrag im Kundenkonto.','participant','email','Dein Zahlungslink · Finde dein Ding · {{amount}}',E'Hallo {{vorname}},\n\nfür dein Kundenkonto ist ein Betrag von {{amount}} offen. Über diesen sicheren Link kannst du die Zahlung mit den in Stripe verfügbaren Zahlungsarten abschließen:\n\n{{payment_link}}\n\nDer Link ist bis {{expiry}} Uhr gültig. Deine Rechnungen und deinen aktuellen Zahlungsstand findest du auch unter „Konto und Finanzen“ im Kundenportal.','active'),
('participant_recovery_link','Kundenportal: Passwort-Link erneut senden','Gestaltete Zugangsmail für die erneute Passwortvergabe.','participant','email','Dein Passwort neu festlegen',E'Hallo {{vorname}},\n\nDein Benutzername: {{login_name}}\nDu kannst dich auch mit deiner E-Mail-Adresse anmelden: {{email}}\n\nÜber den folgenden Link kannst du dein persönliches Passwort selbst festlegen:\n\n{{setup_link}}\n\nFalls du diese E-Mail nicht angefordert hast, kannst du sie ignorieren.','active')
on conflict(template_key) do nothing;

delete from public.communication_automations
where (name='Portal-Zugang nach Vertragsabschluss' and trigger_type='participant_activated')
   or (name='Terminbestätigung nach Verkaufsgespräch' and trigger_type='sales_conversation_completed');
