import SwiftUI
import CoachingCore
import QuickLook
import PDFKit
import UserNotifications
struct AppDocument:Identifiable {let id=UUID();let url:URL}
struct DocumentView:View {
 let document:AppDocument
 @Environment(\.dismiss) var dismiss
 var body:some View {NavigationStack{Group{if document.url.pathExtension.lowercased()=="pdf" {NativePDF(url:document.url)}else{NativePreview(url:document.url)}}.navigationTitle("Dokument").navigationBarTitleDisplayMode(.inline).toolbar{ToolbarItem(placement:.cancellationAction){Button("Schließen"){dismiss()}};ToolbarItem(placement:.primaryAction){ShareLink(item:document.url){Label("Teilen / Sichern",systemImage:"square.and.arrow.up")}}}}
}
}
struct NativePDF:UIViewRepresentable {let url:URL;func makeUIView(context:Context)->PDFView{let view=PDFView();view.autoScales=true;view.document=PDFDocument(url:url);return view};func updateUIView(_ uiView:PDFView,context:Context){}}
struct NativePreview:UIViewControllerRepresentable {let url:URL;func makeCoordinator()->Coordinator{Coordinator(url)};func makeUIViewController(context:Context)->QLPreviewController{let c=QLPreviewController();c.dataSource=context.coordinator;return c};func updateUIViewController(_ c:QLPreviewController,context:Context){};class Coordinator:NSObject,QLPreviewControllerDataSource{let url:URL;init(_ url:URL){self.url=url};func numberOfPreviewItems(in controller:QLPreviewController)->Int{1};func previewController(_ controller:QLPreviewController,previewItemAt index:Int)->QLPreviewItem{url as NSURL}}}
func euro(_ number:JSONValue)->String {number.double.formatted(.currency(code:"EUR").locale(Locale(identifier:"de_DE")))}
func germanDate(_ raw:String)->String {let short=String(raw.prefix(10));let parts=short.split(separator:"-");return parts.count==3 ? "\(parts[2]).\(parts[1]).\(parts[0])":raw}
struct LibraryView:View {
 @EnvironmentObject var store:AppStore
 @State private var search=""
 var body:some View {List{Section{NavigationLink("Rechnungen & Ratenpläne"){InvoicesView()}};Section("Verträge"){if store.overview["contracts"].array.isEmpty{Text("Noch keine Verträge hinterlegt.").foregroundStyle(.secondary)};ForEach(Array(store.overview["contracts"].array.enumerated()),id:\.offset){_,c in VStack(alignment:.leading,spacing:8){Text(c["title"].string.isEmpty ? c["package_name"].string:c["title"].string).font(.headline);Text(c["status"].string=="signed" ? "Abgeschlossen":"\(c["status"].string)");Text(euro(c["amount"]));if !c["signed_at"].isNull{Text("Abschluss: \(germanDate(c["signed_at"].string))").font(.caption)};if !c["document_storage_path"].string.isEmpty{Button("Vertragsdokument öffnen"){Task{await store.showDocument(path:"/api/auth?action=mobile-contract&id=\(c["id"].string)",name:"Vertrag.pdf")}}}}}};Section("Deine Dokumente"){let documents=store.overview["documents"].array.filter{search.isEmpty || $0["original_file_name"].string.localizedCaseInsensitiveContains(search)};if documents.isEmpty {Text("Keine Dokumente vorhanden.").foregroundStyle(.secondary)};ForEach(Array(documents.enumerated()),id:\.offset){_,d in Button{Task{await store.showDocument(path:"/api/customer-records?action=document-download&download=1&documentId=\(d["id"].string)",name:d["original_file_name"].string)}}label:{Label{VStack(alignment:.leading){Text(d["display_title"].string.isEmpty ? d["original_file_name"].string:d["display_title"].string);Text("\(germanDate(d["created_at"].string)) · \(d["week"].int==0 ? "Onboarding":"Woche \(d["week"].int)")").font(.caption).foregroundStyle(.secondary)}}icon:{Image(systemName:"doc.text")}}}}}.navigationTitle("Unterlagen").searchable(text:$search,prompt:"Dokument suchen").refreshable{await store.reload()}}
}
struct InvoicesView:View {
 @EnvironmentObject var store:AppStore
 @State private var search=""
 var body:some View {List {Section("Dein Kontostand"){LabeledContent("Offener Saldo",value:euro(store.overview["finance"]["openBalance"]));LabeledContent("Zahlungseingänge",value:euro(store.overview["finance"]["paidTotal"]))};Section("Rechnungen"){if store.invoices["invoices"].array.isEmpty{Text("Noch keine Rechnungen vorhanden.")};ForEach(Array(store.invoices["invoices"].array.filter{search.isEmpty || $0["invoice_number"].string.localizedCaseInsensitiveContains(search) || $0["description"].string.localizedCaseInsensitiveContains(search)}.enumerated()),id:\.offset){_,invoice in VStack(alignment:.leading,spacing:10){Text(invoice["invoice_number"].string).font(.headline);Text(invoice["description"].string);LabeledContent("Gesamt",value:euro(invoice["gross"]));LabeledContent("Noch offen",value:euro(invoice["open"]));Text("Fällig am \(germanDate(invoice["due_date"].string))").font(.caption);Button("Rechnung ansehen / herunterladen"){Task{await store.showDocument(path:"/api/leads?action=finance-my-pdf&id=\(invoice["id"].string)",name:invoice["invoice_number"].string+".pdf")}}}}};Section("Ratenpläne"){ForEach(Array(store.invoices["plans"].array.enumerated()),id:\.offset){_,plan in DisclosureGroup("Ratenplan · \(euro(plan["total"]))"){LabeledContent("Noch offen",value:euro(plan["open"]));ForEach(Array(plan["rates"].array.enumerated()),id:\.offset){index,rate in VStack(alignment:.leading){Text("Rate \(index+1) · \(euro(rate["amount"]))");Text("Fällig: \(germanDate(rate["due_date"].string)) · offen \(euro(rate["open"]))").font(.caption)}}}}};Section("Gutschriften"){ForEach(Array(store.invoices["credits"].array.enumerated()),id:\.offset){_,credit in Button("\(credit["document_number"].string) · \(euro(credit["amount"]))"){Task{await store.showDocument(path:"/api/leads?action=finance-my-credit-pdf&id=\(credit["id"].string)",name:credit["document_number"].string+".pdf")}}}}}.navigationTitle("Rechnungen & Ratenpläne").searchable(text:$search,prompt:"Rechnung suchen").task{await store.loadInvoices()}.refreshable{await store.loadInvoices();await store.reload()}}
}
struct AppointmentsView:View {
 @EnvironmentObject var store:AppStore
 @Environment(\.openURL) var openURL
 @State private var reminder:String?
 var body:some View {List{if store.overview["appointments"].array.isEmpty{ContentUnavailableView("Noch kein Termin",systemImage:"calendar",description:Text("Vereinbarte Coachingtermine erscheinen hier."))};ForEach(Array(store.overview["appointments"].array.enumerated()),id:\.offset){_,appointment in Section{Text(appointment["title"].string).font(.headline);Text(displayDate(appointment["starts_at"].string));if appointment["status"].string=="cancelled"{Text("Abgesagt").foregroundStyle(.secondary)}else{if let url=CoachingRules.safeExternalURL(appointment["meet_url"].string){Button("An Google Meet teilnehmen"){openURL(url)}.buttonStyle(.borderedProminent)};Button("15 Minuten vorher erinnern"){schedule(appointment)}}}};if let reminder=reminder {Text(reminder).font(.footnote)}}.navigationTitle("Deine Termine").refreshable{await store.reload()}}
 func displayDate(_ raw:String)->String {let f=ISO8601DateFormatter();f.formatOptions=[.withInternetDateTime,.withFractionalSeconds];let date=f.date(from:raw) ?? ISO8601DateFormatter().date(from:raw);return date?.formatted(date:.complete,time:.shortened) ?? raw}
 func schedule(_ appointment:JSONValue){Task{do{let center=UNUserNotificationCenter.current();guard try await center.requestAuthorization(options:[.alert,.sound]) else{reminder="Erinnerungen sind nicht erlaubt. Du kannst sie in den Geräteeinstellungen aktivieren.";return};let f=ISO8601DateFormatter();f.formatOptions=[.withInternetDateTime,.withFractionalSeconds];guard let date=f.date(from:appointment["starts_at"].string) ?? ISO8601DateFormatter().date(from:appointment["starts_at"].string),date.timeIntervalSinceNow>900 else{reminder="Der Termin beginnt in weniger als 15 Minuten oder liegt in der Vergangenheit.";return};let content=UNMutableNotificationContent();content.title="Dein Coachingtermin";content.body="Dein vereinbarter Termin beginnt in 15 Minuten.";content.sound = .default;let request=UNNotificationRequest(identifier:"appointment."+appointment["id"].string,content:content,trigger:UNTimeIntervalNotificationTrigger(timeInterval:date.timeIntervalSinceNow-900,repeats:false));try await center.add(request);reminder="Erinnerung auf diesem Gerät eingerichtet."}catch{reminder=error.localizedDescription}}}
}
struct InsightsView:View {
 @EnvironmentObject var store:AppStore
 var body:some View {List{Section("Wochenreflexionen"){ForEach(Array(store.program["weekReflections"].array.enumerated()),id:\.offset){_,reflection in DisclosureGroup("Woche \(reflection["week"].int)"){ValueTree(value:reflection)}}};Section("Klarheitsverlauf"){ForEach(Array(store.program["clarityHistory"].array.enumerated()),id:\.offset){_,item in ValueTree(value:item)}};ForEach(Array(store.curriculum["records"].array.filter{$0["status"].string=="completed" && !$0["step_id"].string.hasPrefix("week_complete_")}.enumerated()),id:\.offset){_,record in Section("Woche \(record["week"].int)"){Text(record["summary"].string);DisclosureGroup("Deine Ergebnisse"){ValueTree(value:record["structured_data"])}}}}.navigationTitle("Deine Erkenntnisse")}
}
struct ValueTree:View {let value:JSONValue;var body:some View {tree(value)};func tree(_ value:JSONValue)->AnyView{switch value{case .object(let fields):return AnyView(VStack(alignment:.leading,spacing:8){ForEach(fields.keys.sorted().filter{!["id","source_id","source_ids","confirmedBy","version"].contains($0)},id:\.self){key in VStack(alignment:.leading){Text(Self.labels[key] ?? key.replacingOccurrences(of:"_",with:" ").capitalized).font(.caption.bold()).foregroundStyle(.secondary);tree(fields[key]!)} }});case .array(let values):return AnyView(VStack(alignment:.leading,spacing:12){ForEach(Array(values.enumerated()),id:\.offset){_,item in tree(item)}});case .null:return AnyView(EmptyView());default:return AnyView(Text(value.string).textSelection(.enabled))}};static let labels=["summary":"Zusammenfassung","selection":"Deine Auswahl","score":"Klarheit","underlying_need":"Mögliches Bedürfnis","wishes":"Wünsche","raw_wish":"Wunsch im Wortlaut","original_evidence":"Deine Aussage","inference":"Ableitung","confidence":"Sicherheit","confirmed":"Bestätigt","recorded_at":"Erfasst am","note":"Notiz","phase":"Zeitperspektive"]}
